spring.config.import=optional:file:.env[.properties]
spring.application.name=job-assistant

#templates for web
spring.mvc.view.prefix=classpath:/templates/
spring.mvc.view.suffix=.html

#Db properties
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#Spring Security
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

#FlyWay migrations
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#for hh.ru requests
hh.api.base-url=https://api.hh.ru
hh.api.user-agent=${USER_AGENT}